/**
 * Bundle the reader into one self-contained HTML document.
 *
 * Everything is inlined, epub.js included, so the page needs no network. The
 * output is a JS module exporting the HTML as a string, which is the only form a
 * React Native WebView can take directly and is equally usable as an iframe
 * srcdoc on web.
 */
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const result = await build({
  entryPoints: [join(root, "src/webview/reader.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["safari15"],
  minify: true,
  write: false,
  legalComments: "none",
});

const script = result.outputFiles[0].text;

// A script tag inside a template literal would end the HTML early on any literal
// "</script>" in the bundle, so neutralise the only sequence that can do that.
const safe = script.replace(/<\/script>/gi, "<\\/script>");

const html = `<!doctype html>
<html data-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover" />
<style>
  :root { --paper: #faf5ef; --ink: #1b1b1b; }
  html[data-theme="dark"] { --paper: #14110e; --ink: #e8e4dc; }
  html, body { margin: 0; padding: 0; height: 100%; overflow: hidden;
    background: var(--paper); color: var(--ink);
    -webkit-text-size-adjust: 100%; }
  /* Page-turn taps must not start a text selection on the chrome itself; the
     book's own iframe re-enables selection so highlighting still works. */
  body { -webkit-user-select: none; user-select: none; }
  #viewer { height: 100%; width: 100%; }
  #viewer iframe { -webkit-user-select: text; user-select: text; }
</style>
</head>
<body>
<div id="viewer"></div>
<script>${safe}</script>
</body>
</html>`;

writeFileSync(
  join(dist, "index.js"),
  `// Generated by build.mjs. Do not edit.\nexport const readerHtml = ${JSON.stringify(html)};\n`,
);
writeFileSync(
  join(dist, "index.d.ts"),
  `/** Self-contained reader document: epub.js and the bridge, no network needed. */\nexport declare const readerHtml: string;\n`,
);

const kb = (html.length / 1024).toFixed(0);
console.log(`reader bundle: ${kb} KB -> dist/index.js`);
