/**
 * Bundle the reader into one self-contained HTML document.
 *
 * Everything is inlined, epub.js included, so the page needs no network. The
 * output is a JS module exporting the HTML as a string, which is the only form a
 * React Native WebView can take directly and is equally usable as an iframe
 * srcdoc on web.
 */
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

const result = await build({
  entryPoints: [join(root, "src/webview/reader.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["safari15"],
  minify: true,
  write: false,
  legalComments: "none",
});

const script = result.outputFiles[0].text;

// A script tag inside a template literal would end the HTML early on any literal
// "</script>" in the bundle, so neutralise the only sequence that can do that.
const safe = script.replace(/<\/script>/gi, "<\\/script>");

const html = `<!doctype html>
<html data-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover" />
<style>
  :root {
    --paper: #faf5ef; --ink: #1b1b1b;
    /* Page margins as a share of the viewport, which is how print sizes a page.
       Fixed pixel margins look generous on a phone and mean on a tablet. */
    --margin-x: 7vw; --margin-y: 4.5vh;
  }
  html[data-theme="dark"] { --paper: #14110e; --ink: #e8e4dc; }
  html, body { margin: 0; padding: 0; height: 100%; overflow: hidden;
    background: var(--paper); color: var(--ink);
    -webkit-text-size-adjust: 100%; }
  /* Page-turn taps must not start a selection on the chrome; the book's own
     iframe re-enables it so highlighting still works. */
  body { -webkit-user-select: none; user-select: none; }
  /* The page margin lives on <body> as padding, and #viewer fills body's CONTENT
     box. epub.js measures #viewer to work out column geometry, and it only does
     that correctly when #viewer is a plain statically-positioned block whose own
     box is exactly the page area. Padding on #viewer, or wrapping it, or making
     it absolutely positioned, all make the render silently never complete. */
  body {
    box-sizing: border-box;
    padding:
      calc(var(--margin-y) + env(safe-area-inset-top))
      calc(var(--margin-x) + env(safe-area-inset-right))
      calc(var(--margin-y) + env(safe-area-inset-bottom))
      calc(var(--margin-x) + env(safe-area-inset-left));
  }
  #viewer { width: 100%; height: 100%; }
  #viewer iframe { -webkit-user-select: text; user-select: text; }
  /* The commit affordance for a selection. In the HOST document on purpose: it
     floats above the book frame and stays tappable no matter what the frame
     does with events. Amber because that is the colour the saved mark will be. */
  #save-highlight {
    position: fixed; left: 50%; transform: translateX(-50%);
    bottom: calc(26px + env(safe-area-inset-bottom));
    display: none; align-items: center;
    padding: 14px 28px; border: 0; border-radius: 999px;
    background: #f2c94c; color: #1b1b1b;
    font: 600 16px -apple-system, system-ui, sans-serif;
    box-shadow: 0 4px 18px rgba(0, 0, 0, 0.18);
    z-index: 10; cursor: pointer;
  }
</style>
</head>
<body>
<div id="viewer"></div>
<button id="save-highlight" type="button">Save highlight</button>
<script>${safe}</script>
</body>
</html>`;

writeFileSync(
  join(dist, "index.js"),
  `// Generated by build.mjs. Do not edit.\nexport const readerHtml = ${JSON.stringify(html)};\n`,
);
writeFileSync(
  join(dist, "index.d.ts"),
  `/** Self-contained reader document: epub.js and the bridge, no network needed. */\nexport declare const readerHtml: string;\n`,
);

const kb = (html.length / 1024).toFixed(0);
console.log(`reader bundle: ${kb} KB -> dist/index.js`);
