FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html use-cases.html download.html resources.html /usr/share/nginx/html/
COPY docs /usr/share/nginx/html/docs
COPY assets /usr/share/nginx/html/assets
